server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Without  this
        try_files $uri $uri/ /index.html;
        # refreshing /dashboard can produce a 404.
    }
}