services:

  auth:
    build:
      context: ./auth-service
    image: auth-service:local  
    container_name: auth-service
    ports:
      - "8000:8000"
    volumes:
      - ./auth-service:/var/www  
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql
    networks:
      - microservices

  notes:
    build:
      context: ./notes-service
    image: notes-service:local  
    container_name: notes-service
    ports:
      - "8001:8001"
    working_dir: /var/www
    volumes:
      - ./notes-service:/var/www
    command: php artisan serve --host=0.0.0.0 --port=8001
    depends_on:
      - mysql
      - rabbitmq
      - redis
    networks:
      - microservices

  email: 
    build: 
      context: ./email-service 
    image: email-service:local 
    container_name: email-service 
    ports: 
      - "8002:8002" 
    volumes: 
      - ./email-service:/var/www 
    working_dir: /var/www 
    command: php artisan serve --host=0.0.0.0 --port=8002 
    depends_on: 
      - mysql 
      - rabbitmq 
      - redis 
    networks: 
      - microservices 

  frontend:
    build:
      context: ./frontend 
    image: frontend:local
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www
    working_dir: /var/www
    networks:
      - microservices   


  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservices

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices

  notes-consumer:
    image: notes-service:local
    container_name: notes-consumer
    working_dir: /var/www
    command: php artisan rabbitmq:consume-users
    depends_on:
      - rabbitmq
      - mysql
    restart: unless-stopped
    volumes:
      - ./notes-service:/var/www
    networks:
      - microservices

  notes-consumer-loggedinmsg:
    image: notes-service:local
    container_name: notes-consumer-loggedinmsg
    working_dir: /var/www
    command: php artisan rabbitmq:consume-user-logged-in
    depends_on:
      - rabbitmq
      - mysql
    restart: unless-stopped
    volumes:
      - ./notes-service:/var/www
    networks:
      - microservices

  email-user-consumer: 
    image: email-service:local 
    container_name: email-user-consumer 
    working_dir: /var/www 
    command: php artisan rabbitmq:consume-user-created
    depends_on: 
      - email 
      - mysql 
      - rabbitmq 
    restart: unless-stopped 
    volumes: 
      - ./email-service:/var/www 
    networks: 
      - microservices

  email-note-consumer: 
    image: email-service:local 
    container_name: email-note-consumer 
    working_dir: /var/www 
    command: php artisan rabbitmq:consume-note-created 
    depends_on: 
      - email 
      - mysql 
      - rabbitmq 
      - redis 
    restart: unless-stopped 
    volumes: 
      - ./email-service:/var/www 
    networks: 
      - microservices  

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - microservices       

  notes-worker:
    image: notes-service:local
    container_name: notes-worker
    working_dir: /var/www
    command: php artisan queue:work redis --tries=3 --timeout=90
    restart: unless-stopped
    volumes:
      - ./notes-service:/var/www
    depends_on:
      - redis
      - mysql
    networks:
      - microservices

  email-worker: 
    image: email-service:local 
    container_name: email-worker 
    working_dir: /var/www 
    command: php artisan queue:work redis --tries=3 --timeout=120 
    restart: unless-stopped 
    volumes: 
      - ./email-service:/var/www 
    depends_on: 
      - email 
      - mysql 
      - redis 
    networks: 
      - microservices       
  
  # =========================================================
  # API GATEWAY 
  # =========================================================

  gateway:
    build:
      context: ./gateway
    container_name: api-gateway
    ports:
      - "9000:80"
    depends_on:
      - auth
      - notes
    networks:
      - microservices

  
networks:
  microservices:
    driver: bridge

volumes:
  mysql-data:
