name: CI/CD Pipeline

on:
  push:
    branches:
      - main

##########################################################
# QUALITY CHECKS
##########################################################

jobs:

  quality:

    name: Quality - ${{ matrix.service }}

    runs-on: ubuntu-latest

    ##################################################
      # Configure Environment
    ##################################################

    env:
      DB_CONNECTION: ${{ matrix.connection }}

      AUTH_DB_HOST: 127.0.0.1
      AUTH_DB_PORT: 3306
      AUTH_DB_DATABASE: auth_testing
      AUTH_DB_USERNAME: root
      AUTH_DB_PASSWORD: root

      NOTES_DB_HOST: 127.0.0.1
      NOTES_DB_PORT: 3306
      NOTES_DB_DATABASE: note_testing
      NOTES_DB_USERNAME: root
      NOTES_DB_PASSWORD: root

      CACHE_STORE: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync

    strategy:
      fail-fast: false
      matrix:
        include:
          - service: auth-service
            connection: auth_db
            database: auth_testing

          - service: notes-service
            connection: notes_db
            database: note_testing

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    services:

      mysql:
        image: mysql:8.0

        env:
          MYSQL_ROOT_PASSWORD: root

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      ##################################################
      # Checkout
      ##################################################

      - uses: actions/checkout@v4

      ##################################################
      # PHP
      ##################################################

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring,pdo_mysql,redis
          coverage: none

      ##################################################
      # Environment
      ##################################################

      - name: Copy Environment
        run: cp .env.testing .env

      ##################################################
      # Composer
      ##################################################

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Show current directory
        run: |
          pwd
          ls -la

      - name: Verify bootstrap/app.php
        run: |
          ls -la bootstrap
          cat bootstrap/app.php  

      - name: Check loaded providers
        run: php artisan tinker --execute="dump(app()->getLoadedProviders());"    

      ##################################################
      # Create Databases
      ##################################################

      - name: Create Test Database
        run: |
          mysql -h127.0.0.1 -uroot -proot \
          -e "CREATE DATABASE IF NOT EXISTS ${{ matrix.database }};"

      

      

      ##################################################
      # Laravel
      ##################################################

      - name: Generate Application Key
        run: php artisan key:generate --env=testing

      - name: Clear Cache
        run: php artisan optimize:clear --env=testing

      - name: Run Migrations
        run: php artisan migrate --force --env=testing

      ##################################################
      # Code Quality
      ##################################################

      - name: Laravel Pint
        run: vendor/bin/pint --test

      ##################################################
      # Debug
      ##################################################

      - name: Laravel About
        run: php artisan about

      - name: Route List
        run: php artisan route:list

      - name: Show environment
        run: php artisan env   

      ##################################################
      # Tests
      ##################################################

      - name: Unit Tests
        run: php artisan test --testsuite=Unit

      - name: Feature Tests
        run: php artisan test --testsuite=Feature

      ##################################################
      # Swagger
      ##################################################

      - name: Generate Swagger
        run: php artisan l5-swagger:generate

##########################################################
# BUILD & PUSH IMAGES
##########################################################

  docker:

    name: Docker - ${{ matrix.image }}

    needs: quality

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:

          - image: auth-service
            context: ./auth-service

          - image: notes-service
            context: ./notes-service

          - image: gateway
            context: ./gateway

    steps:

      ##################################################
      # Checkout
      ##################################################

      - uses: actions/checkout@v4

      ##################################################
      # Login
      ##################################################

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ##################################################
      # Build
      ##################################################

      - name: Build Docker Image
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:latest \
          ${{ matrix.context }}

      ##################################################
      # Push
      ##################################################

      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:latest


##########################################################
# DEPLOY TO AWS EC2
##########################################################

  deploy:

    name: Deploy to AWS EC2

    needs: docker

    runs-on: ubuntu-latest

    steps:

      ##################################################
      # Checkout
      ##################################################

      - uses: actions/checkout@v4

      ##################################################
      # Deploy via SSH
      ##################################################

      - name: Deploy Application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
              -u "${{ secrets.DOCKER_USERNAME }}" \
              --password-stdin

            cd ~/notes-observability-microservices

            git pull origin main

            docker compose pull

            docker images

            docker compose up -d --force-recreate --remove-orphans

            docker compose ps

            docker image prune -f

            docker system prune -f        